// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: redis.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAccessLevel int32

const (
	UserAccessLevel_USER_ACCESS_LEVEL_UNSPECIFIED   UserAccessLevel = 0
	UserAccessLevel_USER_ACCESS_LEVEL_CLUSTER_ADMIN UserAccessLevel = 1
	UserAccessLevel_USER_ACCESS_LEVEL_READ_WRITE    UserAccessLevel = 3
	UserAccessLevel_USER_ACCESS_LEVEL_READ          UserAccessLevel = 4
)

// Enum value maps for UserAccessLevel.
var (
	UserAccessLevel_name = map[int32]string{
		0: "USER_ACCESS_LEVEL_UNSPECIFIED",
		1: "USER_ACCESS_LEVEL_CLUSTER_ADMIN",
		3: "USER_ACCESS_LEVEL_READ_WRITE",
		4: "USER_ACCESS_LEVEL_READ",
	}
	UserAccessLevel_value = map[string]int32{
		"USER_ACCESS_LEVEL_UNSPECIFIED":   0,
		"USER_ACCESS_LEVEL_CLUSTER_ADMIN": 1,
		"USER_ACCESS_LEVEL_READ_WRITE":    3,
		"USER_ACCESS_LEVEL_READ":          4,
	}
)

func (x UserAccessLevel) Enum() *UserAccessLevel {
	p := new(UserAccessLevel)
	*p = x
	return p
}

func (x UserAccessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAccessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_redis_proto_enumTypes[0].Descriptor()
}

func (UserAccessLevel) Type() protoreflect.EnumType {
	return &file_redis_proto_enumTypes[0]
}

func (x UserAccessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAccessLevel.Descriptor instead.
func (UserAccessLevel) EnumDescriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  []byte                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastLogin     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Rules         []*UserACLRule         `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_redis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPasswordHash() []byte {
	if x != nil {
		return x.PasswordHash
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *User) GetRules() []*UserACLRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UserACLRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         UserAccessLevel        `protobuf:"varint,1,opt,name=level,proto3,enum=types.UserAccessLevel" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserACLRule) Reset() {
	*x = UserACLRule{}
	mi := &file_redis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserACLRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserACLRule) ProtoMessage() {}

func (x *UserACLRule) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserACLRule.ProtoReflect.Descriptor instead.
func (*UserACLRule) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{1}
}

func (x *UserACLRule) GetLevel() UserAccessLevel {
	if x != nil {
		return x.Level
	}
	return UserAccessLevel_USER_ACCESS_LEVEL_UNSPECIFIED
}

var File_redis_proto protoreflect.FileDescriptor

const file_redis_proto_rawDesc = "" +
	"\n" +
	"\vredis.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x02\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\fR\fpasswordHash\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"last_login\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12(\n" +
	"\x05rules\x18\x06 \x03(\v2\x12.types.UserACLRuleR\x05rules\";\n" +
	"\vUserACLRule\x12,\n" +
	"\x05level\x18\x01 \x01(\x0e2\x16.types.UserAccessLevelR\x05level*\x97\x01\n" +
	"\x0fUserAccessLevel\x12!\n" +
	"\x1dUSER_ACCESS_LEVEL_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fUSER_ACCESS_LEVEL_CLUSTER_ADMIN\x10\x01\x12 \n" +
	"\x1cUSER_ACCESS_LEVEL_READ_WRITE\x10\x03\x12\x1a\n" +
	"\x16USER_ACCESS_LEVEL_READ\x10\x04B/Z-github.com/bluesky-social/kvdb/internal/typesb\x06proto3"

var (
	file_redis_proto_rawDescOnce sync.Once
	file_redis_proto_rawDescData []byte
)

func file_redis_proto_rawDescGZIP() []byte {
	file_redis_proto_rawDescOnce.Do(func() {
		file_redis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redis_proto_rawDesc), len(file_redis_proto_rawDesc)))
	})
	return file_redis_proto_rawDescData
}

var file_redis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_redis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_redis_proto_goTypes = []any{
	(UserAccessLevel)(0),          // 0: types.UserAccessLevel
	(*User)(nil),                  // 1: types.User
	(*UserACLRule)(nil),           // 2: types.UserACLRule
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_redis_proto_depIdxs = []int32{
	3, // 0: types.User.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: types.User.last_login:type_name -> google.protobuf.Timestamp
	2, // 2: types.User.rules:type_name -> types.UserACLRule
	0, // 3: types.UserACLRule.level:type_name -> types.UserAccessLevel
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_redis_proto_init() }
func file_redis_proto_init() {
	if File_redis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redis_proto_rawDesc), len(file_redis_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_redis_proto_goTypes,
		DependencyIndexes: file_redis_proto_depIdxs,
		EnumInfos:         file_redis_proto_enumTypes,
		MessageInfos:      file_redis_proto_msgTypes,
	}.Build()
	File_redis_proto = out.File
	file_redis_proto_goTypes = nil
	file_redis_proto_depIdxs = nil
}
