// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: redis.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserKind int32

const (
	UserKind_USER_KIND_UNSPECIFIED   UserKind = 0
	UserKind_USER_KIND_CLUSTER_ADMIN UserKind = 1
	UserKind_USER_KIND_NORMAL        UserKind = 2
)

// Enum value maps for UserKind.
var (
	UserKind_name = map[int32]string{
		0: "USER_KIND_UNSPECIFIED",
		1: "USER_KIND_CLUSTER_ADMIN",
		2: "USER_KIND_NORMAL",
	}
	UserKind_value = map[string]int32{
		"USER_KIND_UNSPECIFIED":   0,
		"USER_KIND_CLUSTER_ADMIN": 1,
		"USER_KIND_NORMAL":        2,
	}
)

func (x UserKind) Enum() *UserKind {
	p := new(UserKind)
	*p = x
	return p
}

func (x UserKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserKind) Descriptor() protoreflect.EnumDescriptor {
	return file_redis_proto_enumTypes[0].Descriptor()
}

func (UserKind) Type() protoreflect.EnumType {
	return &file_redis_proto_enumTypes[0]
}

func (x UserKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserKind.Descriptor instead.
func (UserKind) EnumDescriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  []byte                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Kind          UserKind               `protobuf:"varint,3,opt,name=kind,proto3,enum=types.UserKind" json:"kind,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastLogin     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_redis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPasswordHash() []byte {
	if x != nil {
		return x.PasswordHash
	}
	return nil
}

func (x *User) GetKind() UserKind {
	if x != nil {
		return x.Kind
	}
	return UserKind_USER_KIND_UNSPECIFIED
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

var File_redis_proto protoreflect.FileDescriptor

const file_redis_proto_rawDesc = "" +
	"\n" +
	"\vredis.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\fR\fpasswordHash\x12#\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x0f.types.UserKindR\x04kind\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"last_login\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin*X\n" +
	"\bUserKind\x12\x19\n" +
	"\x15USER_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17USER_KIND_CLUSTER_ADMIN\x10\x01\x12\x14\n" +
	"\x10USER_KIND_NORMAL\x10\x02B/Z-github.com/bluesky-social/kvdb/internal/typesb\x06proto3"

var (
	file_redis_proto_rawDescOnce sync.Once
	file_redis_proto_rawDescData []byte
)

func file_redis_proto_rawDescGZIP() []byte {
	file_redis_proto_rawDescOnce.Do(func() {
		file_redis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redis_proto_rawDesc), len(file_redis_proto_rawDesc)))
	})
	return file_redis_proto_rawDescData
}

var file_redis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_redis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_redis_proto_goTypes = []any{
	(UserKind)(0),                 // 0: types.UserKind
	(*User)(nil),                  // 1: types.User
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_redis_proto_depIdxs = []int32{
	0, // 0: types.User.kind:type_name -> types.UserKind
	2, // 1: types.User.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: types.User.last_login:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_redis_proto_init() }
func file_redis_proto_init() {
	if File_redis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redis_proto_rawDesc), len(file_redis_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_redis_proto_goTypes,
		DependencyIndexes: file_redis_proto_depIdxs,
		EnumInfos:         file_redis_proto_enumTypes,
		MessageInfos:      file_redis_proto_msgTypes,
	}.Build()
	File_redis_proto = out.File
	file_redis_proto_goTypes = nil
	file_redis_proto_depIdxs = nil
}
