// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: redis.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAccessLevel int32

const (
	UserAccessLevel_USER_ACCESS_LEVEL_UNSPECIFIED   UserAccessLevel = 0
	UserAccessLevel_USER_ACCESS_LEVEL_CLUSTER_ADMIN UserAccessLevel = 1
	UserAccessLevel_USER_ACCESS_LEVEL_READ_WRITE    UserAccessLevel = 3
	UserAccessLevel_USER_ACCESS_LEVEL_READ          UserAccessLevel = 4
)

// Enum value maps for UserAccessLevel.
var (
	UserAccessLevel_name = map[int32]string{
		0: "USER_ACCESS_LEVEL_UNSPECIFIED",
		1: "USER_ACCESS_LEVEL_CLUSTER_ADMIN",
		3: "USER_ACCESS_LEVEL_READ_WRITE",
		4: "USER_ACCESS_LEVEL_READ",
	}
	UserAccessLevel_value = map[string]int32{
		"USER_ACCESS_LEVEL_UNSPECIFIED":   0,
		"USER_ACCESS_LEVEL_CLUSTER_ADMIN": 1,
		"USER_ACCESS_LEVEL_READ_WRITE":    3,
		"USER_ACCESS_LEVEL_READ":          4,
	}
)

func (x UserAccessLevel) Enum() *UserAccessLevel {
	p := new(UserAccessLevel)
	*p = x
	return p
}

func (x UserAccessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAccessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_redis_proto_enumTypes[0].Descriptor()
}

func (UserAccessLevel) Type() protoreflect.EnumType {
	return &file_redis_proto_enumTypes[0]
}

func (x UserAccessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAccessLevel.Descriptor instead.
func (UserAccessLevel) EnumDescriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  []byte                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	LastLogin     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Rules         []*UserACLRule         `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_redis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPasswordHash() []byte {
	if x != nil {
		return x.PasswordHash
	}
	return nil
}

func (x *User) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *User) GetRules() []*UserACLRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UserACLRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         UserAccessLevel        `protobuf:"varint,1,opt,name=level,proto3,enum=types.UserAccessLevel" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserACLRule) Reset() {
	*x = UserACLRule{}
	mi := &file_redis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserACLRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserACLRule) ProtoMessage() {}

func (x *UserACLRule) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserACLRule.ProtoReflect.Descriptor instead.
func (*UserACLRule) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{1}
}

func (x *UserACLRule) GetLevel() UserAccessLevel {
	if x != nil {
		return x.Level
	}
	return UserAccessLevel_USER_ACCESS_LEVEL_UNSPECIFIED
}

type ObjectMeta struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Created *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	Updated *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Expires *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires,proto3,oneof" json:"expires,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*ObjectMeta_Basic
	//	*ObjectMeta_Set
	//	*ObjectMeta_SortedSet
	//	*ObjectMeta_List
	//	*ObjectMeta_ListItem
	Type          isObjectMeta_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_redis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectMeta) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *ObjectMeta) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *ObjectMeta) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

func (x *ObjectMeta) GetType() isObjectMeta_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ObjectMeta) GetBasic() *BasicObjectMeta {
	if x != nil {
		if x, ok := x.Type.(*ObjectMeta_Basic); ok {
			return x.Basic
		}
	}
	return nil
}

func (x *ObjectMeta) GetSet() *SetMeta {
	if x != nil {
		if x, ok := x.Type.(*ObjectMeta_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *ObjectMeta) GetSortedSet() *SortedSetMeta {
	if x != nil {
		if x, ok := x.Type.(*ObjectMeta_SortedSet); ok {
			return x.SortedSet
		}
	}
	return nil
}

func (x *ObjectMeta) GetList() *ListMeta {
	if x != nil {
		if x, ok := x.Type.(*ObjectMeta_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *ObjectMeta) GetListItem() *ListItemMeta {
	if x != nil {
		if x, ok := x.Type.(*ObjectMeta_ListItem); ok {
			return x.ListItem
		}
	}
	return nil
}

type isObjectMeta_Type interface {
	isObjectMeta_Type()
}

type ObjectMeta_Basic struct {
	Basic *BasicObjectMeta `protobuf:"bytes,4,opt,name=basic,proto3,oneof"`
}

type ObjectMeta_Set struct {
	Set *SetMeta `protobuf:"bytes,5,opt,name=set,proto3,oneof"`
}

type ObjectMeta_SortedSet struct {
	SortedSet *SortedSetMeta `protobuf:"bytes,6,opt,name=sorted_set,json=sortedSet,proto3,oneof"`
}

type ObjectMeta_List struct {
	List *ListMeta `protobuf:"bytes,7,opt,name=list,proto3,oneof"`
}

type ObjectMeta_ListItem struct {
	ListItem *ListItemMeta `protobuf:"bytes,8,opt,name=list_item,json=listItem,proto3,oneof"`
}

func (*ObjectMeta_Basic) isObjectMeta_Type() {}

func (*ObjectMeta_Set) isObjectMeta_Type() {}

func (*ObjectMeta_SortedSet) isObjectMeta_Type() {}

func (*ObjectMeta_List) isObjectMeta_Type() {}

func (*ObjectMeta_ListItem) isObjectMeta_Type() {}

type BasicObjectMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumChunks     uint32                 `protobuf:"varint,1,opt,name=num_chunks,json=numChunks,proto3" json:"num_chunks,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicObjectMeta) Reset() {
	*x = BasicObjectMeta{}
	mi := &file_redis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicObjectMeta) ProtoMessage() {}

func (x *BasicObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicObjectMeta.ProtoReflect.Descriptor instead.
func (*BasicObjectMeta) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{3}
}

func (x *BasicObjectMeta) GetNumChunks() uint32 {
	if x != nil {
		return x.NumChunks
	}
	return 0
}

func (x *BasicObjectMeta) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type SetMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumItems      uint64                 `protobuf:"varint,1,opt,name=num_items,json=numItems,proto3" json:"num_items,omitempty"`
	NumChunks     uint32                 `protobuf:"varint,2,opt,name=num_chunks,json=numChunks,proto3" json:"num_chunks,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMeta) Reset() {
	*x = SetMeta{}
	mi := &file_redis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMeta) ProtoMessage() {}

func (x *SetMeta) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMeta.ProtoReflect.Descriptor instead.
func (*SetMeta) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{4}
}

func (x *SetMeta) GetNumItems() uint64 {
	if x != nil {
		return x.NumItems
	}
	return 0
}

func (x *SetMeta) GetNumChunks() uint32 {
	if x != nil {
		return x.NumChunks
	}
	return 0
}

func (x *SetMeta) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type SortedSetMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumItems      uint64                 `protobuf:"varint,1,opt,name=num_items,json=numItems,proto3" json:"num_items,omitempty"`
	NumChunks     uint32                 `protobuf:"varint,2,opt,name=num_chunks,json=numChunks,proto3" json:"num_chunks,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortedSetMeta) Reset() {
	*x = SortedSetMeta{}
	mi := &file_redis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortedSetMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortedSetMeta) ProtoMessage() {}

func (x *SortedSetMeta) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortedSetMeta.ProtoReflect.Descriptor instead.
func (*SortedSetMeta) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{5}
}

func (x *SortedSetMeta) GetNumItems() uint64 {
	if x != nil {
		return x.NumItems
	}
	return 0
}

func (x *SortedSetMeta) GetNumChunks() uint32 {
	if x != nil {
		return x.NumChunks
	}
	return 0
}

func (x *SortedSetMeta) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ListMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumItems      uint64                 `protobuf:"varint,1,opt,name=num_items,json=numItems,proto3" json:"num_items,omitempty"`
	ItemHead      string                 `protobuf:"bytes,2,opt,name=item_head,json=itemHead,proto3" json:"item_head,omitempty"`
	ItemTail      string                 `protobuf:"bytes,3,opt,name=item_tail,json=itemTail,proto3" json:"item_tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeta) Reset() {
	*x = ListMeta{}
	mi := &file_redis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeta) ProtoMessage() {}

func (x *ListMeta) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeta.ProtoReflect.Descriptor instead.
func (*ListMeta) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{6}
}

func (x *ListMeta) GetNumItems() uint64 {
	if x != nil {
		return x.NumItems
	}
	return 0
}

func (x *ListMeta) GetItemHead() string {
	if x != nil {
		return x.ItemHead
	}
	return ""
}

func (x *ListMeta) GetItemTail() string {
	if x != nil {
		return x.ItemTail
	}
	return ""
}

type ListItemMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Next          string                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Previous      string                 `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	NumChunks     uint32                 `protobuf:"varint,4,opt,name=num_chunks,json=numChunks,proto3" json:"num_chunks,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemMeta) Reset() {
	*x = ListItemMeta{}
	mi := &file_redis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemMeta) ProtoMessage() {}

func (x *ListItemMeta) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemMeta.ProtoReflect.Descriptor instead.
func (*ListItemMeta) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{7}
}

func (x *ListItemMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListItemMeta) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *ListItemMeta) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *ListItemMeta) GetNumChunks() uint32 {
	if x != nil {
		return x.NumChunks
	}
	return 0
}

func (x *ListItemMeta) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type UIDItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        string                 `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Score         *float32               `protobuf:"fixed32,3,opt,name=score,proto3,oneof" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIDItem) Reset() {
	*x = UIDItem{}
	mi := &file_redis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIDItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIDItem) ProtoMessage() {}

func (x *UIDItem) ProtoReflect() protoreflect.Message {
	mi := &file_redis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIDItem.ProtoReflect.Descriptor instead.
func (*UIDItem) Descriptor() ([]byte, []int) {
	return file_redis_proto_rawDescGZIP(), []int{8}
}

func (x *UIDItem) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *UIDItem) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UIDItem) GetScore() float32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

var File_redis_proto protoreflect.FileDescriptor

const file_redis_proto_rawDesc = "" +
	"\n" +
	"\vredis.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\fR\fpasswordHash\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x129\n" +
	"\n" +
	"last_login\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12(\n" +
	"\x05rules\x18\x06 \x03(\v2\x12.types.UserACLRuleR\x05rules\";\n" +
	"\vUserACLRule\x12,\n" +
	"\x05level\x18\x01 \x01(\x0e2\x16.types.UserAccessLevelR\x05level\"\xad\x03\n" +
	"\n" +
	"ObjectMeta\x124\n" +
	"\acreated\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x124\n" +
	"\aupdated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aupdated\x129\n" +
	"\aexpires\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aexpires\x88\x01\x01\x12.\n" +
	"\x05basic\x18\x04 \x01(\v2\x16.types.BasicObjectMetaH\x00R\x05basic\x12\"\n" +
	"\x03set\x18\x05 \x01(\v2\x0e.types.SetMetaH\x00R\x03set\x125\n" +
	"\n" +
	"sorted_set\x18\x06 \x01(\v2\x14.types.SortedSetMetaH\x00R\tsortedSet\x12%\n" +
	"\x04list\x18\a \x01(\v2\x0f.types.ListMetaH\x00R\x04list\x122\n" +
	"\tlist_item\x18\b \x01(\v2\x13.types.ListItemMetaH\x00R\blistItemB\x06\n" +
	"\x04typeB\n" +
	"\n" +
	"\b_expires\"O\n" +
	"\x0fBasicObjectMeta\x12\x1d\n" +
	"\n" +
	"num_chunks\x18\x01 \x01(\rR\tnumChunks\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\"d\n" +
	"\aSetMeta\x12\x1b\n" +
	"\tnum_items\x18\x01 \x01(\x04R\bnumItems\x12\x1d\n" +
	"\n" +
	"num_chunks\x18\x02 \x01(\rR\tnumChunks\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\"j\n" +
	"\rSortedSetMeta\x12\x1b\n" +
	"\tnum_items\x18\x01 \x01(\x04R\bnumItems\x12\x1d\n" +
	"\n" +
	"num_chunks\x18\x02 \x01(\rR\tnumChunks\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\"a\n" +
	"\bListMeta\x12\x1b\n" +
	"\tnum_items\x18\x01 \x01(\x04R\bnumItems\x12\x1b\n" +
	"\titem_head\x18\x02 \x01(\tR\bitemHead\x12\x1b\n" +
	"\titem_tail\x18\x03 \x01(\tR\bitemTail\"\x8c\x01\n" +
	"\fListItemMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x03 \x01(\tR\bprevious\x12\x1d\n" +
	"\n" +
	"num_chunks\x18\x04 \x01(\rR\tnumChunks\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x04R\tsizeBytes\"X\n" +
	"\aUIDItem\x12\x16\n" +
	"\x06member\x18\x01 \x01(\tR\x06member\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x19\n" +
	"\x05score\x18\x03 \x01(\x02H\x00R\x05score\x88\x01\x01B\b\n" +
	"\x06_score*\x97\x01\n" +
	"\x0fUserAccessLevel\x12!\n" +
	"\x1dUSER_ACCESS_LEVEL_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fUSER_ACCESS_LEVEL_CLUSTER_ADMIN\x10\x01\x12 \n" +
	"\x1cUSER_ACCESS_LEVEL_READ_WRITE\x10\x03\x12\x1a\n" +
	"\x16USER_ACCESS_LEVEL_READ\x10\x04B/Z-github.com/bluesky-social/kvdb/internal/typesb\x06proto3"

var (
	file_redis_proto_rawDescOnce sync.Once
	file_redis_proto_rawDescData []byte
)

func file_redis_proto_rawDescGZIP() []byte {
	file_redis_proto_rawDescOnce.Do(func() {
		file_redis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redis_proto_rawDesc), len(file_redis_proto_rawDesc)))
	})
	return file_redis_proto_rawDescData
}

var file_redis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_redis_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_redis_proto_goTypes = []any{
	(UserAccessLevel)(0),          // 0: types.UserAccessLevel
	(*User)(nil),                  // 1: types.User
	(*UserACLRule)(nil),           // 2: types.UserACLRule
	(*ObjectMeta)(nil),            // 3: types.ObjectMeta
	(*BasicObjectMeta)(nil),       // 4: types.BasicObjectMeta
	(*SetMeta)(nil),               // 5: types.SetMeta
	(*SortedSetMeta)(nil),         // 6: types.SortedSetMeta
	(*ListMeta)(nil),              // 7: types.ListMeta
	(*ListItemMeta)(nil),          // 8: types.ListItemMeta
	(*UIDItem)(nil),               // 9: types.UIDItem
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_redis_proto_depIdxs = []int32{
	10, // 0: types.User.created:type_name -> google.protobuf.Timestamp
	10, // 1: types.User.last_login:type_name -> google.protobuf.Timestamp
	2,  // 2: types.User.rules:type_name -> types.UserACLRule
	0,  // 3: types.UserACLRule.level:type_name -> types.UserAccessLevel
	10, // 4: types.ObjectMeta.created:type_name -> google.protobuf.Timestamp
	10, // 5: types.ObjectMeta.updated:type_name -> google.protobuf.Timestamp
	10, // 6: types.ObjectMeta.expires:type_name -> google.protobuf.Timestamp
	4,  // 7: types.ObjectMeta.basic:type_name -> types.BasicObjectMeta
	5,  // 8: types.ObjectMeta.set:type_name -> types.SetMeta
	6,  // 9: types.ObjectMeta.sorted_set:type_name -> types.SortedSetMeta
	7,  // 10: types.ObjectMeta.list:type_name -> types.ListMeta
	8,  // 11: types.ObjectMeta.list_item:type_name -> types.ListItemMeta
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_redis_proto_init() }
func file_redis_proto_init() {
	if File_redis_proto != nil {
		return
	}
	file_redis_proto_msgTypes[2].OneofWrappers = []any{
		(*ObjectMeta_Basic)(nil),
		(*ObjectMeta_Set)(nil),
		(*ObjectMeta_SortedSet)(nil),
		(*ObjectMeta_List)(nil),
		(*ObjectMeta_ListItem)(nil),
	}
	file_redis_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redis_proto_rawDesc), len(file_redis_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_redis_proto_goTypes,
		DependencyIndexes: file_redis_proto_depIdxs,
		EnumInfos:         file_redis_proto_enumTypes,
		MessageInfos:      file_redis_proto_msgTypes,
	}.Build()
	File_redis_proto = out.File
	file_redis_proto_goTypes = nil
	file_redis_proto_depIdxs = nil
}
